<?php

namespace Hafael\Easyrec\Tests\Api;


use Hafael\Easyrec\Api\Api;

require_once(__DIR__ . '/../../vendor/autoload.php');

abstract class AbstractApiTest extends \PHPUnit\Framework\TestCase
{
    const VERSION = '1.1';
    const BASE_URL = 'http://localhost:8081/easyrec-web/api/1.1/json/';
    const API_KEY = '6491d97a8a0c3f7d07b1df5d83a83521';
    const TENANT_ID = 'EASYREC_DEMO';
    const API_VERSION = '1.1';
    const TOKEN = '970217a66b67ea7f0145ab82f2a7ec92';

    /**
     * @var Api|null
     */
    protected $api = null;

    protected function setUp()
    {
        parent::setUp();

        if ($this->api instanceof Api) {
            return;
        }

        $this->createApi();
    }

    public abstract function createApi();

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        // clean memory
        $this->api = null;
    }

    public function testAdd()
    {
        $result = 1 + 1;
        $this->assertEquals(2, $result, 'Wrong add 1 vs 1');
        $this->assertEquals(3, $result, 'Wrong add 1 vs 1');
    }
}